name: build-n-deploy

on:
  push:
    branches:
      - "*"

jobs:
  build-n-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js v19.6.0
        uses: actions/setup-node@v2
        with:
          node-version: '19.6.0'

      - name: Install Dependencies
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm install

      - name: Build
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          docker build -t my-react-app .
          docker run -p 3000:3000 my-react-app
